### ISSUE TITLE
Warning: Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-local_glossary_wordimport#1]
Attempting to export a glossary, I am getting a lot of PHP warnings like this:

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m39/moodle/local/glossary_wordimport/index.php:56) in /home/mudrd8mz/www/mdk/m39/moodle/lib/filelib.php on line 2469

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m39/moodle/local/glossary_wordimport/index.php:56) in /home/mudrd8mz/www/mdk/m39/moodle/lib/filelib.php on line 2501

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m39/moodle/local/glossary_wordimport/index.php:56) in /home/mudrd8mz/www/mdk/m39/moodle/lib/filelib.php on line 2502

Warning: Cannot modify header information - headers already sent by (output started at /home/mudrd8mz/www/mdk/m39/moodle/local/glossary_wordimport/index.php:56) in /home/mudrd8mz/www/mdk/m39/moodle/lib/filelib.php on line 2503

(continues)

**Comment by mudrd8mz** [comment]
The fix is simple. The `$OUTPUT` should be started only after the `if ($action == 'export') {` is processed.

p.s. This makes me believe that PHP developer debugging has not been enabled while you were testing this. Always make sure to have it on at your dev machine.

**Comment by ecampbell** [comment]
This is fixed in version 0.7.0.
