### ISSUE TITLE
Embedded images not exported

### ISSUE THREAD

**Issue by mudrd8mz** [ecampbell/moodle-local_glossary_wordimport#3]
I made a glossary record with an image embedded into the definition. When opened in Word, the exported document does not contain the image - only a red cross is shown.

**Comment by ecampbell** [comment]
This is correct if unsatisfactory behaviour. A VBA macro must be run on the exported Word file in order to convert image data back into embedded images.

**Comment by mudrd8mz** [comment]
> A VBA macro must be run on the exported Word file in order to convert image data back into embedded images.

Is that something I missed in the plugin description?
